In [24]:
import pandas as pd
import numpy as np

In [25]:
TRAIN_DIM = 1000
TEST_DIM = 10

In [26]:
data = pd.read_csv('src/main/resources/train_triplets.txt', sep="\t", header=None)
data.columns = ["user", "song", "play_count"]

In [27]:
data.head()

                                       user                song  play_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995           1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAPDEY12A81C210A9           1
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B           2
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFNSP12AF72A0E22           1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFOVM12A58A7D494           1

In [28]:
print("Users: ", data['user'].unique().size, "\tSongs: ", data['song'].unique().size, "\tTriplets: ", data.shape[0])

Users:  1019318 	Songs:  384546 	Triplets:  48373586

In [29]:
users = data['user'].unique()

In [30]:
train = data[data['user'].isin(users[:TRAIN_DIM])]

In [31]:
train

,user,song,play_count
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAPDEY12A81C210A9,1
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFNSP12AF72A0E22,1
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFOVM12A58A7D494,1
...,...,...,...
49626,d31161da4ece1468da84c933a3f3a8af7ef4ef0a,SOUFWEW12AB0180EB7,5
49627,d31161da4ece1468da84c933a3f3a8af7ef4ef0a,SOVJTAK12AF72A3D70,1
49628,d31161da4ece1468da84c933a3f3a8af7ef4ef0a,SOWNBFZ12A58A78A77,1
49629,d31161da4ece1468da84c933a3f3a8af7ef4ef0a,SOXAZAV12A6D4FAC53,1
49630,d31161da4ece1468da84c933a3f3a8af7ef4ef0a,SOZKLQR12AF72A45C9,2

In [32]:
# Extracting test_full and using it instead of whole data in the cells below saves a lot of time
test_full = data[data['user'].isin(users[TRAIN_DIM:TRAIN_DIM+TEST_DIM])]

In [33]:
test_full

,user,song,play_count
49631,bebc003f4829f97cac534729b0e6f67886453a27,SOACPBY12A8C13FEF9,1
49632,bebc003f4829f97cac534729b0e6f67886453a27,SOAMKRU12A58A814CB,1
49633,bebc003f4829f97cac534729b0e6f67886453a27,SOCJVDJ12A8C1375E3,1
49634,bebc003f4829f97cac534729b0e6f67886453a27,SOCMJQF12AF72A566A,2
49635,bebc003f4829f97cac534729b0e6f67886453a27,SOEZEOB12A6D4F6CEB,2
...,...,...,...
50008,f0cd8df775b33e171e2f1f5454338e2f82feaa89,SOVPARS12AC468B131,1
50009,f0cd8df775b33e171e2f1f5454338e2f82feaa89,SOXNGDE12AB018C7A4,1
50010,f0cd8df775b33e171e2f1f5454338e2f82feaa89,SOXUTTP12A6D4F480F,2
50011,f0cd8df775b33e171e2f1f5454338e2f82feaa89,SOYJYFW12A8C130E52,2
50012,f0cd8df775b33e171e2f1f5454338e2f82feaa89,SOZBDZN12A8C130C7B,2

In [34]:
for user in users[TRAIN_DIM:TRAIN_DIM+TEST_DIM]:
    print(test_full[test_full['user'] == user].shape[0], int(np.ceil(test_full[test_full['user'] == user].shape[0]/2)))

23 12
74 37
10 5
14 7
48 24
61 31
49 25
15 8
54 27
34 17

In [35]:
test = pd.DataFrame(columns=data.columns)
test_labels = pd.DataFrame(columns=data.columns)
for user in users[TRAIN_DIM:TRAIN_DIM+TEST_DIM]:
   test = pd.concat([test,test_full[test_full['user'] == user][:int(np.ceil(test_full[test_full['user'] == user].shape[0]/2))]], axis=0)
   test_labels = pd.concat([test_labels,test_full[test_full['user'] == user][int(np.ceil(test_full[test_full['user'] == user].shape[0]/2)):]], axis=0)

In [36]:
test

                                           user                song play_count
49631  bebc003f4829f97cac534729b0e6f67886453a27  SOACPBY12A8C13FEF9          1
49632  bebc003f4829f97cac534729b0e6f67886453a27  SOAMKRU12A58A814CB          1
49633  bebc003f4829f97cac534729b0e6f67886453a27  SOCJVDJ12A8C1375E3          1
49634  bebc003f4829f97cac534729b0e6f67886453a27  SOCMJQF12AF72A566A          2
49635  bebc003f4829f97cac534729b0e6f67886453a27  SOEZEOB12A6D4F6CEB          2
...                                         ...                 ...        ...
49991  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOJVDCO12A6D4FA24B          5
49992  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOJYOEX12A6D4F9043          1
49993  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOKCWUE12A8AE47124          2
49994  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOKIYKH12AB0186B3C          1
49995  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOLFDCL12A8C141E21          2

[193 rows x 3 columns]

In [37]:
test_labels

                                           user                song play_count
49643  bebc003f4829f97cac534729b0e6f67886453a27  SOMWMKR12A67020C6C          1
49644  bebc003f4829f97cac534729b0e6f67886453a27  SOMYXWV12A8C14232E          1
49645  bebc003f4829f97cac534729b0e6f67886453a27  SONJJXC12A6701D7BD          1
49646  bebc003f4829f97cac534729b0e6f67886453a27  SOOBDRI12A8C132391          1
49647  bebc003f4829f97cac534729b0e6f67886453a27  SOOJWBY12A67020C60          2
...                                         ...                 ...        ...
50008  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOVPARS12AC468B131          1
50009  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOXNGDE12AB018C7A4          1
50010  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOXUTTP12A6D4F480F          2
50011  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOYJYFW12A8C130E52          2
50012  f0cd8df775b33e171e2f1f5454338e2f82feaa89  SOZBDZN12A8C130C7B          2

[189 rows x 3 columns]

In [38]:
for user in users[TRAIN_DIM:TRAIN_DIM+TEST_DIM]:
    print(test_full[test_full['user'] == user].shape[0], test[test['user'] == user].shape[0], test_labels[test_labels['user'] == user].shape[0])

23 12 11
74 37 37
10 5 5
14 7 7
48 24 24
61 31 30
49 25 24
15 8 7
54 27 27
34 17 17

In [39]:
train.to_csv(r'src/main/resources/train_'+str(TRAIN_DIM)+'_'+str(TEST_DIM)+'.txt', header=None, index=None, sep='\t', mode='w')
test.to_csv(r'src/main/resources/test_'+str(TRAIN_DIM)+'_'+str(TEST_DIM)+'.txt', header=None, index=None, sep='\t', mode='w')
test_labels.to_csv(r'src/main/resources/test_labels_'+str(TRAIN_DIM)+'_'+str(TEST_DIM)+'.txt', header=None, index=None, sep='\t', mode='w')