In [17]:
import pandas as pd
import numpy as np

In [18]:
TRAIN_DIM = 500
TEST_DIM = 100

In [19]:
data = pd.read_csv('src/main/resources/train_triplets.txt', sep="\t", header=None)
data.columns = ["user", "song", "play_count"]

In [20]:
data.head()

                                       user                song  play_count
0  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAKIMP12A8C130995           1
1  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOAPDEY12A81C210A9           1
2  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBBMDR12A8C13253B           2
3  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFNSP12AF72A0E22           1
4  b80344d063b5ccb3212f76538f3d9e43d87dca9e  SOBFOVM12A58A7D494           1

In [21]:
print("Users: ", data['user'].unique().size, "\tSongs: ", data['song'].unique().size, "\tTriplets: ", data.shape[0])

Users:  1019318 	Songs:  384546 	Triplets:  48373586

In [22]:
users = data['user'].unique()

In [23]:
train = data[data['user'].isin(users[:TRAIN_DIM])]

In [24]:
train

,user,song,play_count
0,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAKIMP12A8C130995,1
1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOAPDEY12A81C210A9,1
2,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBBMDR12A8C13253B,2
3,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFNSP12AF72A0E22,1
4,b80344d063b5ccb3212f76538f3d9e43d87dca9e,SOBFOVM12A58A7D494,1
...,...,...,...
24887,df576258e114403b482a2f27f2c5619df4c27a74,SOPAMVK12A8AE48E11,2
24888,df576258e114403b482a2f27f2c5619df4c27a74,SOPPTRY12AF72A8EB8,1
24889,df576258e114403b482a2f27f2c5619df4c27a74,SOQZYQH12A8AE468E5,1
24890,df576258e114403b482a2f27f2c5619df4c27a74,SOYABSZ12A81C1FEAC,5
24891,df576258e114403b482a2f27f2c5619df4c27a74,SOYVYAG12AB018A344,1

In [25]:
# Extracting test_full and using it instead of whole data in the cells below saves a lot of time
test_full = data[data['user'].isin(users[TRAIN_DIM:TRAIN_DIM+TEST_DIM])]

In [26]:
test_full

,user,song,play_count
24892,a84dab2d0dd967d002cea226fbc0a6446bbb7014,SOABNPW12A6D4FC9B5,1
24893,a84dab2d0dd967d002cea226fbc0a6446bbb7014,SOAKMYN12A8C1316C5,1
24894,a84dab2d0dd967d002cea226fbc0a6446bbb7014,SOAYLRC12A8C138C32,2
24895,a84dab2d0dd967d002cea226fbc0a6446bbb7014,SOBAAAB12A6D4F95A5,1
24896,a84dab2d0dd967d002cea226fbc0a6446bbb7014,SOBKKUJ12A6D4FC8AB,1
...,...,...,...
29235,7aec2eb348ca2deace19d4829e4f4ddf48e3f912,SOQYADC12A8C13E41C,1
29236,7aec2eb348ca2deace19d4829e4f4ddf48e3f912,SOUTTSQ12A6D4F43FA,4
29237,7aec2eb348ca2deace19d4829e4f4ddf48e3f912,SOUVTSM12AC468F6A7,1
29238,7aec2eb348ca2deace19d4829e4f4ddf48e3f912,SOXZLEQ12A8C133427,18
29239,7aec2eb348ca2deace19d4829e4f4ddf48e3f912,SOYEYNW12AB017F385,1

In [27]:
for user in users[TRAIN_DIM:TRAIN_DIM+TEST_DIM]:
    print(test_full[test_full['user'] == user].shape[0], int(np.ceil(test_full[test_full['user'] == user].shape[0]/2)))

54 27
77 39
110 55
147 74
13 7
17 9
15 8
24 12
31 16
23 12
28 14
16 8
13 7
20 10
10 5
14 7
54 27
16 8
25 13
11 6
97 49
21 11
20 10
13 7
17 9
17 9
14 7
45 23
57 29
110 55
54 27
158 79
209 105
33 17
130 65
19 10
21 11
83 42
32 16
37 19
79 40
17 9
110 55
60 30
11 6
45 23
42 21
24 12
15 8
17 9
229 115
40 20
17 9
14 7
16 8
87 44
45 23
17 9
17 9
19 10
72 36
45 23
43 22
32 16
21 11
85 43
33 17
91 46
11 6
56 28
24 12
18 9
56 28
47 24
40 20
33 17
27 14
20 10
47 24
12 6
17 9
205 103
19 10
14 7
28 14
55 28
16 8
13 7
43 22
87 44
24 12
11 6
19 10
44 22
27 14
14 7
17 9
24 12
21 11
11 6

In [28]:
test = pd.DataFrame(columns=data.columns)
test_labels = pd.DataFrame(columns=data.columns)
for user in users[TRAIN_DIM:TRAIN_DIM+TEST_DIM]:
   test = pd.concat([test,test_full[test_full['user'] == user][:int(np.ceil(test_full[test_full['user'] == user].shape[0]/2))]], axis=0)
   test_labels = pd.concat([test_labels,test_full[test_full['user'] == user][int(np.ceil(test_full[test_full['user'] == user].shape[0]/2)):]], axis=0)

In [29]:
test

                                           user                song play_count
24892  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SOABNPW12A6D4FC9B5          1
24893  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SOAKMYN12A8C1316C5          1
24894  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SOAYLRC12A8C138C32          2
24895  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SOBAAAB12A6D4F95A5          1
24896  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SOBKKUJ12A6D4FC8AB          1
...                                         ...                 ...        ...
29230  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOETVSH12A81C21DA6          5
29231  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOFGSLS12A6D4F9C6A          9
29232  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOJFCAC12AB0186C16          1
29233  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOKYPQN12AF72A1F53          3
29234  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOPHWDH12A58A77846          4

[2204 rows x 3 columns]

In [30]:
test_labels

                                           user                song play_count
24919  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SOMLECN12AAF3B46F6          1
24920  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SOMXPHT12AB0182BE7          1
24921  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SONGVPK12A8C13CF8F          1
24922  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SONRRQH12AC3DFA45F          1
24923  a84dab2d0dd967d002cea226fbc0a6446bbb7014  SONSWER12AF72A4D35          1
...                                         ...                 ...        ...
29235  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOQYADC12A8C13E41C          1
29236  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOUTTSQ12A6D4F43FA          4
29237  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOUVTSM12AC468F6A7          1
29238  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOXZLEQ12A8C133427         18
29239  7aec2eb348ca2deace19d4829e4f4ddf48e3f912  SOYEYNW12AB017F385          1

[2144 rows x 3 columns]

In [31]:
for user in users[TRAIN_DIM:TRAIN_DIM+TEST_DIM]:
    print(test_full[test_full['user'] == user].shape[0], test[test['user'] == user].shape[0], test_labels[test_labels['user'] == user].shape[0])

54 27 27
77 39 38
110 55 55
147 74 73
13 7 6
17 9 8
15 8 7
24 12 12
31 16 15
23 12 11
28 14 14
16 8 8
13 7 6
20 10 10
10 5 5
14 7 7
54 27 27
16 8 8
25 13 12
11 6 5
97 49 48
21 11 10
20 10 10
13 7 6
17 9 8
17 9 8
14 7 7
45 23 22
57 29 28
110 55 55
54 27 27
158 79 79
209 105 104
33 17 16
130 65 65
19 10 9
21 11 10
83 42 41
32 16 16
37 19 18
79 40 39
17 9 8
110 55 55
60 30 30
11 6 5
45 23 22
42 21 21
24 12 12
15 8 7
17 9 8
229 115 114
40 20 20
17 9 8
14 7 7
16 8 8
87 44 43
45 23 22
17 9 8
17 9 8
19 10 9
72 36 36
45 23 22
43 22 21
32 16 16
21 11 10
85 43 42
33 17 16
91 46 45
11 6 5
56 28 28
24 12 12
18 9 9
56 28 28
47 24 23
40 20 20
33 17 16
27 14 13
20 10 10
47 24 23
12 6 6
17 9 8
205 103 102
19 10 9
14 7 7
28 14 14
55 28 27
16 8 8
13 7 6
43 22 21
87 44 43
24 12 12
11 6 5
19 10 9
44 22 22
27 14 13
14 7 7
17 9 8
24 12 12
21 11 10
11 6 5

In [32]:
train.to_csv(r'src/main/resources/train_'+str(TRAIN_DIM)+'_'+str(TEST_DIM)+'.txt', header=None, index=None, sep='\t', mode='w')
test.to_csv(r'src/main/resources/test_'+str(TRAIN_DIM)+'_'+str(TEST_DIM)+'.txt', header=None, index=None, sep='\t', mode='w')
test_labels.to_csv(r'src/main/resources/test_labels_'+str(TRAIN_DIM)+'_'+str(TEST_DIM)+'.txt', header=None, index=None, sep='\t', mode='w')